/* Pure-JS crypto for the Wafflelist Pebble app.
 *
 * PebbleKit JS has no WebCrypto, so this module reimplements exactly the
 * primitives the Wafflelist web client uses (src/lib/crypto.ts):
 *   - PBKDF2-SHA256 (user id derivation, 600k iterations)
 *   - HKDF-SHA256 (encryption key + signing seed derivation)
 *   - AES-256-GCM (todo blob encryption)
 *   - Ed25519 (request signing; RFC 8032, matches WebCrypto)
 *
 * Everything here is verified byte-for-byte against Node's WebCrypto by
 * test/crypto.test.cjs. ES5 only - this runs inside the Pebble mobile
 * app's JS sandbox.
 *
 * The Ed25519 implementation is derived from TweetNaCl.js (public domain).
 * SHA constant tables are generated by tools/gen-sha-constants.mjs.
 */

'use strict';

/* ---------------- byte helpers ---------------- */

function utf8Encode(str) {
  var out = [];
  for (var i = 0; i < str.length; i++) {
    var c = str.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdbff && i + 1 < str.length) {
      var lo = str.charCodeAt(i + 1);
      if (lo >= 0xdc00 && lo <= 0xdfff) {
        c = 0x10000 + ((c - 0xd800) << 10) + (lo - 0xdc00);
        i++;
      }
    }
    if (c < 0x80) {
      out.push(c);
    } else if (c < 0x800) {
      out.push(0xc0 | (c >> 6), 0x80 | (c & 63));
    } else if (c < 0x10000) {
      out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63));
    } else {
      out.push(0xf0 | (c >> 18), 0x80 | ((c >> 12) & 63), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63));
    }
  }
  return new Uint8Array(out);
}

function utf8Decode(bytes) {
  var out = '';
  var i = 0;
  while (i < bytes.length) {
    var b = bytes[i];
    var c;
    if (b < 0x80) {
      c = b; i += 1;
    } else if ((b & 0xe0) === 0xc0) {
      c = ((b & 31) << 6) | (bytes[i + 1] & 63); i += 2;
    } else if ((b & 0xf0) === 0xe0) {
      c = ((b & 15) << 12) | ((bytes[i + 1] & 63) << 6) | (bytes[i + 2] & 63); i += 3;
    } else {
      c = ((b & 7) << 18) | ((bytes[i + 1] & 63) << 12) | ((bytes[i + 2] & 63) << 6) | (bytes[i + 3] & 63); i += 4;
    }
    if (c >= 0x10000) {
      c -= 0x10000;
      out += String.fromCharCode(0xd800 + (c >> 10), 0xdc00 + (c & 0x3ff));
    } else {
      out += String.fromCharCode(c);
    }
  }
  return out;
}

var HEX = '0123456789abcdef';

function bytesToHex(bytes) {
  var out = '';
  for (var i = 0; i < bytes.length; i++) {
    out += HEX[bytes[i] >> 4] + HEX[bytes[i] & 15];
  }
  return out;
}

function hexToBytes(hex) {
  var out = new Uint8Array(hex.length / 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

var B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

function bytesToBase64(bytes) {
  var out = '';
  var i;
  for (i = 0; i + 2 < bytes.length; i += 3) {
    var n = (bytes[i] << 16) | (bytes[i + 1] << 8) | bytes[i + 2];
    out += B64[(n >> 18) & 63] + B64[(n >> 12) & 63] + B64[(n >> 6) & 63] + B64[n & 63];
  }
  var rem = bytes.length - i;
  if (rem === 1) {
    out += B64[bytes[i] >> 2] + B64[(bytes[i] << 4) & 63] + '==';
  } else if (rem === 2) {
    out += B64[bytes[i] >> 2] + B64[((bytes[i] << 4) | (bytes[i + 1] >> 4)) & 63] + B64[(bytes[i + 1] << 2) & 63] + '=';
  }
  return out;
}

var B64_REV = (function () {
  var rev = {};
  for (var i = 0; i < 64; i++) rev[B64[i]] = i;
  return rev;
})();

function base64ToBytes(str) {
  str = str.replace(/[\s=]+$/, '').replace(/\s+/g, '');
  var len = Math.floor(str.length * 3 / 4);
  var out = new Uint8Array(len);
  var o = 0;
  for (var i = 0; i + 3 < str.length; i += 4) {
    var n = (B64_REV[str[i]] << 18) | (B64_REV[str[i + 1]] << 12) | (B64_REV[str[i + 2]] << 6) | B64_REV[str[i + 3]];
    out[o++] = (n >> 16) & 0xff;
    out[o++] = (n >> 8) & 0xff;
    out[o++] = n & 0xff;
  }
  var rem = str.length - i;
  if (rem === 2) {
    out[o++] = (B64_REV[str[i]] << 2) | (B64_REV[str[i + 1]] >> 4);
  } else if (rem === 3) {
    var m = (B64_REV[str[i]] << 10) | (B64_REV[str[i + 1]] << 4) | (B64_REV[str[i + 2]] >> 2);
    out[o++] = (m >> 8) & 0xff;
    out[o++] = m & 0xff;
  }
  return out;
}

function concatBytes() {
  var total = 0, i;
  for (i = 0; i < arguments.length; i++) total += arguments[i].length;
  var out = new Uint8Array(total);
  var off = 0;
  for (i = 0; i < arguments.length; i++) {
    out.set(arguments[i], off);
    off += arguments[i].length;
  }
  return out;
}

/* ---------------- SHA-256 ---------------- */
/* Constant tables generated by tools/gen-sha-constants.mjs */

var SHA256_K = [0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2];
var SHA256_H0 = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];

var sha256W = new Int32Array(64);

// Processes len bytes (multiple of 64) starting at data[off] into state[8].
function sha256Blocks(state, data, off, len) {
  var w = sha256W;
  var end = off + len;
  for (var p = off; p < end; p += 64) {
    var i, x, y;
    for (i = 0; i < 16; i++) {
      w[i] = (data[p + 4 * i] << 24) | (data[p + 4 * i + 1] << 16) | (data[p + 4 * i + 2] << 8) | data[p + 4 * i + 3];
    }
    for (i = 16; i < 64; i++) {
      x = w[i - 15];
      y = w[i - 2];
      w[i] = (w[i - 16]
        + (((x >>> 7) | (x << 25)) ^ ((x >>> 18) | (x << 14)) ^ (x >>> 3))
        + w[i - 7]
        + (((y >>> 17) | (y << 15)) ^ ((y >>> 19) | (y << 13)) ^ (y >>> 10))) | 0;
    }
    var a = state[0], b = state[1], c = state[2], d = state[3];
    var e = state[4], f = state[5], g = state[6], h = state[7];
    for (i = 0; i < 64; i++) {
      var t1 = (h
        + (((e >>> 6) | (e << 26)) ^ ((e >>> 11) | (e << 21)) ^ ((e >>> 25) | (e << 7)))
        + ((e & f) ^ (~e & g))
        + SHA256_K[i] + w[i]) | 0;
      var t2 = ((((a >>> 2) | (a << 30)) ^ ((a >>> 13) | (a << 19)) ^ ((a >>> 22) | (a << 10)))
        + ((a & b) ^ (a & c) ^ (b & c))) | 0;
      h = g; g = f; f = e; e = (d + t1) | 0;
      d = c; c = b; b = a; a = (t1 + t2) | 0;
    }
    state[0] = (state[0] + a) | 0;
    state[1] = (state[1] + b) | 0;
    state[2] = (state[2] + c) | 0;
    state[3] = (state[3] + d) | 0;
    state[4] = (state[4] + e) | 0;
    state[5] = (state[5] + f) | 0;
    state[6] = (state[6] + g) | 0;
    state[7] = (state[7] + h) | 0;
  }
}

function sha256StateToBytes(state, out) {
  for (var i = 0; i < 8; i++) {
    out[4 * i] = (state[i] >>> 24) & 0xff;
    out[4 * i + 1] = (state[i] >>> 16) & 0xff;
    out[4 * i + 2] = (state[i] >>> 8) & 0xff;
    out[4 * i + 3] = state[i] & 0xff;
  }
  return out;
}

function sha256(msg) {
  var state = new Int32Array(SHA256_H0);
  var len = msg.length;
  var full = len - (len % 64);
  sha256Blocks(state, msg, 0, full);
  var rem = len - full;
  var tail = new Uint8Array(rem + 9 > 64 ? 128 : 64);
  for (var i = 0; i < rem; i++) tail[i] = msg[full + i];
  tail[rem] = 0x80;
  var tl = tail.length;
  var bitsHi = Math.floor(len / 0x20000000);
  var bitsLo = (len * 8) >>> 0;
  tail[tl - 8] = (bitsHi >>> 24) & 0xff;
  tail[tl - 7] = (bitsHi >>> 16) & 0xff;
  tail[tl - 6] = (bitsHi >>> 8) & 0xff;
  tail[tl - 5] = bitsHi & 0xff;
  tail[tl - 4] = (bitsLo >>> 24) & 0xff;
  tail[tl - 3] = (bitsLo >>> 16) & 0xff;
  tail[tl - 2] = (bitsLo >>> 8) & 0xff;
  tail[tl - 1] = bitsLo & 0xff;
  sha256Blocks(state, tail, 0, tl);
  return sha256StateToBytes(state, new Uint8Array(32));
}

/* ---------------- HMAC-SHA256 ---------------- */

function hmacSha256Init(key) {
  if (key.length > 64) key = sha256(key);
  var ipad = new Uint8Array(64);
  var opad = new Uint8Array(64);
  for (var i = 0; i < 64; i++) {
    var k = i < key.length ? key[i] : 0;
    ipad[i] = k ^ 0x36;
    opad[i] = k ^ 0x5c;
  }
  var iState = new Int32Array(SHA256_H0);
  sha256Blocks(iState, ipad, 0, 64);
  var oState = new Int32Array(SHA256_H0);
  sha256Blocks(oState, opad, 0, 64);
  return { iState: iState, oState: oState };
}

// Generic HMAC for arbitrary-length messages.
function hmacSha256(key, msg) {
  var ctx = hmacSha256Init(key);

  var state = new Int32Array(ctx.iState);
  var len = msg.length;
  var full = len - (len % 64);
  sha256Blocks(state, msg, 0, full);
  var rem = len - full;
  var tail = new Uint8Array(rem + 9 > 64 ? 128 : 64);
  for (var i = 0; i < rem; i++) tail[i] = msg[full + i];
  tail[rem] = 0x80;
  var total = 64 + len; // ipad block + message
  var tl = tail.length;
  var bitsHi = Math.floor(total / 0x20000000);
  var bitsLo = (total * 8) >>> 0;
  tail[tl - 8] = (bitsHi >>> 24) & 0xff;
  tail[tl - 7] = (bitsHi >>> 16) & 0xff;
  tail[tl - 6] = (bitsHi >>> 8) & 0xff;
  tail[tl - 5] = bitsHi & 0xff;
  tail[tl - 4] = (bitsLo >>> 24) & 0xff;
  tail[tl - 3] = (bitsLo >>> 16) & 0xff;
  tail[tl - 2] = (bitsLo >>> 8) & 0xff;
  tail[tl - 1] = bitsLo & 0xff;
  sha256Blocks(state, tail, 0, tl);
  var inner = sha256StateToBytes(state, new Uint8Array(32));

  return hmacFinishOuter(ctx.oState, inner);
}

// outer = SHA256(opad-state, digest32). One padded block.
var hmacOuterBlock = new Uint8Array(64);

function hmacFinishOuter(oState, digest32) {
  var blk = hmacOuterBlock;
  for (var i = 0; i < 32; i++) blk[i] = digest32[i];
  blk[32] = 0x80;
  for (i = 33; i < 62; i++) blk[i] = 0;
  blk[62] = 0x03; // (64 + 32) * 8 = 768 bits
  blk[63] = 0x00;
  var state = new Int32Array(oState);
  sha256Blocks(state, blk, 0, 64);
  return sha256StateToBytes(state, new Uint8Array(32));
}

/* ---------------- PBKDF2-SHA256 (single 32-byte block) ---------------- */

// Runs `count` iterations of the PBKDF2 inner loop using precomputed HMAC
// midstates: 2 SHA-256 compressions per iteration.
function pbkdf2Round(ctx, u, t, count) {
  var innerBlk = new Uint8Array(64);
  innerBlk[32] = 0x80;
  innerBlk[62] = 0x03; // 768-bit total length, same shape as hmacFinishOuter
  var outerBlk = new Uint8Array(64);
  outerBlk[32] = 0x80;
  outerBlk[62] = 0x03;
  var state = new Int32Array(8);
  var i, j;
  for (i = 0; i < count; i++) {
    for (j = 0; j < 32; j++) innerBlk[j] = u[j];
    state.set(ctx.iState);
    sha256Blocks(state, innerBlk, 0, 64);
    sha256StateToBytes(state, u);
    for (j = 0; j < 32; j++) outerBlk[j] = u[j];
    state.set(ctx.oState);
    sha256Blocks(state, outerBlk, 0, 64);
    sha256StateToBytes(state, u);
    for (j = 0; j < 32; j++) t[j] ^= u[j];
  }
}

function pbkdf2Sha256(password, salt, iterations) {
  var ctx = hmacSha256Init(password);
  var u = hmacSha256(password, concatBytes(salt, new Uint8Array([0, 0, 0, 1])));
  var t = new Uint8Array(u);
  pbkdf2Round(ctx, u, t, iterations - 1);
  return t;
}

// Chunked variant so the (multi-second) 600k-iteration derivation doesn't
// block the PebbleKit JS thread in one go. cb(result), progress(done, total).
function pbkdf2Sha256Async(password, salt, iterations, cb, progress) {
  var ctx = hmacSha256Init(password);
  var u = hmacSha256(password, concatBytes(salt, new Uint8Array([0, 0, 0, 1])));
  var t = new Uint8Array(u);
  var remaining = iterations - 1;
  var done = 1;
  var CHUNK = 25000;

  function step() {
    var n = remaining < CHUNK ? remaining : CHUNK;
    pbkdf2Round(ctx, u, t, n);
    remaining -= n;
    done += n;
    if (progress) progress(done, iterations);
    if (remaining > 0) {
      setTimeout(step, 0);
    } else {
      cb(t);
    }
  }
  setTimeout(step, 0);
}

/* ---------------- HKDF-SHA256 (32-byte output) ---------------- */

function hkdfSha256(ikm, salt, info) {
  var prk = hmacSha256(salt, ikm);
  return hmacSha256(prk, concatBytes(info, new Uint8Array([1])));
}

/* ---------------- SHA-512 (for Ed25519) ---------------- */

var SHA512_KH = [0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2, 0xca273ece, 0xd186b8c7, 0xeada7dd6, 0xf57d4f7f, 0x06f067aa, 0x0a637dc5, 0x113f9804, 0x1b710b35, 0x28db77f5, 0x32caab7b, 0x3c9ebe0a, 0x431d67c4, 0x4cc5d4be, 0x597f299c, 0x5fcb6fab, 0x6c44198c];
var SHA512_KL = [0xd728ae22, 0x23ef65cd, 0xec4d3b2f, 0x8189dbbc, 0xf348b538, 0xb605d019, 0xaf194f9b, 0xda6d8118, 0xa3030242, 0x45706fbe, 0x4ee4b28c, 0xd5ffb4e2, 0xf27b896f, 0x3b1696b1, 0x25c71235, 0xcf692694, 0x9ef14ad2, 0x384f25e3, 0x8b8cd5b5, 0x77ac9c65, 0x592b0275, 0x6ea6e483, 0xbd41fbd4, 0x831153b5, 0xee66dfab, 0x2db43210, 0x98fb213f, 0xbeef0ee4, 0x3da88fc2, 0x930aa725, 0xe003826f, 0x0a0e6e70, 0x46d22ffc, 0x5c26c926, 0x5ac42aed, 0x9d95b3df, 0x8baf63de, 0x3c77b2a8, 0x47edaee6, 0x1482353b, 0x4cf10364, 0xbc423001, 0xd0f89791, 0x0654be30, 0xd6ef5218, 0x5565a910, 0x5771202a, 0x32bbd1b8, 0xb8d2d0c8, 0x5141ab53, 0xdf8eeb99, 0xe19b48a8, 0xc5c95a63, 0xe3418acb, 0x7763e373, 0xd6b2b8a3, 0x5defb2fc, 0x43172f60, 0xa1f0ab72, 0x1a6439ec, 0x23631e28, 0xde82bde9, 0xb2c67915, 0xe372532b, 0xea26619c, 0x21c0c207, 0xcde0eb1e, 0xee6ed178, 0x72176fba, 0xa2c898a6, 0xbef90dae, 0x131c471b, 0x23047d84, 0x40c72493, 0x15c9bebc, 0x9c100d4c, 0xcb3e42b6, 0xfc657e2a, 0x3ad6faec, 0x4a475817];
var SHA512_HH = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
var SHA512_HL = [0xf3bcc908, 0x84caa73b, 0xfe94f82b, 0x5f1d36f1, 0xade682d1, 0x2b3e6c1f, 0xfb41bd6b, 0x137e2179];

function sha512(msg) {
  // 64-bit words as parallel hi/lo 32-bit arrays.
  var hh = new Int32Array(SHA512_HH);
  var hl = new Int32Array(SHA512_HL);
  var wh = new Int32Array(80);
  var wl = new Int32Array(80);

  var len = msg.length;
  var padded = new Uint8Array((Math.floor((len + 16) / 128) + 1) * 128);
  padded.set(msg);
  padded[len] = 0x80;
  var pl = padded.length;
  var bitsHi = Math.floor(len / 0x20000000);
  var bitsLo = (len * 8) >>> 0;
  padded[pl - 8] = (bitsHi >>> 24) & 0xff;
  padded[pl - 7] = (bitsHi >>> 16) & 0xff;
  padded[pl - 6] = (bitsHi >>> 8) & 0xff;
  padded[pl - 5] = bitsHi & 0xff;
  padded[pl - 4] = (bitsLo >>> 24) & 0xff;
  padded[pl - 3] = (bitsLo >>> 16) & 0xff;
  padded[pl - 2] = (bitsLo >>> 8) & 0xff;
  padded[pl - 1] = bitsLo & 0xff;

  for (var p = 0; p < pl; p += 128) {
    var i;
    for (i = 0; i < 16; i++) {
      var o = p + 8 * i;
      wh[i] = (padded[o] << 24) | (padded[o + 1] << 16) | (padded[o + 2] << 8) | padded[o + 3];
      wl[i] = (padded[o + 4] << 24) | (padded[o + 5] << 16) | (padded[o + 6] << 8) | padded[o + 7];
    }
    for (i = 16; i < 80; i++) {
      // s0 = rotr1 ^ rotr8 ^ shr7 of w[i-15]
      var xh = wh[i - 15], xl = wl[i - 15];
      var s0h = (((xh >>> 1) | (xl << 31)) ^ ((xh >>> 8) | (xl << 24)) ^ (xh >>> 7)) >>> 0;
      var s0l = (((xl >>> 1) | (xh << 31)) ^ ((xl >>> 8) | (xh << 24)) ^ ((xl >>> 7) | (xh << 25))) >>> 0;
      // s1 = rotr19 ^ rotr61 ^ shr6 of w[i-2]
      var yh = wh[i - 2], yl = wl[i - 2];
      var s1h = (((yh >>> 19) | (yl << 13)) ^ ((yl >>> 29) | (yh << 3)) ^ (yh >>> 6)) >>> 0;
      var s1l = (((yl >>> 19) | (yh << 13)) ^ ((yh >>> 29) | (yl << 3)) ^ ((yl >>> 6) | (yh << 26))) >>> 0;
      var lo = (wl[i - 16] >>> 0) + s0l + (wl[i - 7] >>> 0) + s1l;
      var hi = (wh[i - 16] >>> 0) + s0h + (wh[i - 7] >>> 0) + s1h + Math.floor(lo / 0x100000000);
      wh[i] = hi | 0;
      wl[i] = lo | 0;
    }

    var ah = hh[0], al = hl[0], bh = hh[1], bl = hl[1], ch = hh[2], cl = hl[2], dh = hh[3], dl = hl[3];
    var eh = hh[4], el = hl[4], fh = hh[5], fl = hl[5], gh = hh[6], gl = hl[6], hh7 = hh[7], hl7 = hl[7];

    for (i = 0; i < 80; i++) {
      // S1 = rotr14 ^ rotr18 ^ rotr41 of e
      var S1h = (((eh >>> 14) | (el << 18)) ^ ((eh >>> 18) | (el << 14)) ^ ((el >>> 9) | (eh << 23))) >>> 0;
      var S1l = (((el >>> 14) | (eh << 18)) ^ ((el >>> 18) | (eh << 14)) ^ ((eh >>> 9) | (el << 23))) >>> 0;
      var chh = ((eh & fh) ^ (~eh & gh)) >>> 0;
      var chl = ((el & fl) ^ (~el & gl)) >>> 0;
      var t1l = (hl7 >>> 0) + S1l + chl + (SHA512_KL[i] >>> 0) + (wl[i] >>> 0);
      var t1h = (hh7 >>> 0) + S1h + chh + (SHA512_KH[i] >>> 0) + (wh[i] >>> 0) + Math.floor(t1l / 0x100000000);
      t1l = t1l >>> 0;
      // S0 = rotr28 ^ rotr34 ^ rotr39 of a
      var S0h = (((ah >>> 28) | (al << 4)) ^ ((al >>> 2) | (ah << 30)) ^ ((al >>> 7) | (ah << 25))) >>> 0;
      var S0l = (((al >>> 28) | (ah << 4)) ^ ((ah >>> 2) | (al << 30)) ^ ((ah >>> 7) | (al << 25))) >>> 0;
      var majh = ((ah & bh) ^ (ah & ch) ^ (bh & ch)) >>> 0;
      var majl = ((al & bl) ^ (al & cl) ^ (bl & cl)) >>> 0;
      var t2l = S0l + majl;
      var t2h = S0h + majh + Math.floor(t2l / 0x100000000);
      t2l = t2l >>> 0;

      hh7 = gh; hl7 = gl; gh = fh; gl = fl; fh = eh; fl = el;
      var nel = (dl >>> 0) + t1l;
      eh = ((dh >>> 0) + t1h + Math.floor(nel / 0x100000000)) | 0;
      el = nel | 0;
      dh = ch; dl = cl; ch = bh; cl = bl; bh = ah; bl = al;
      var nal = t1l + t2l;
      ah = (t1h + t2h + Math.floor(nal / 0x100000000)) | 0;
      al = nal | 0;
    }

    var sl;
    sl = (hl[0] >>> 0) + (al >>> 0); hh[0] = (hh[0] + ah + Math.floor(sl / 0x100000000)) | 0; hl[0] = sl | 0;
    sl = (hl[1] >>> 0) + (bl >>> 0); hh[1] = (hh[1] + bh + Math.floor(sl / 0x100000000)) | 0; hl[1] = sl | 0;
    sl = (hl[2] >>> 0) + (cl >>> 0); hh[2] = (hh[2] + ch + Math.floor(sl / 0x100000000)) | 0; hl[2] = sl | 0;
    sl = (hl[3] >>> 0) + (dl >>> 0); hh[3] = (hh[3] + dh + Math.floor(sl / 0x100000000)) | 0; hl[3] = sl | 0;
    sl = (hl[4] >>> 0) + (el >>> 0); hh[4] = (hh[4] + eh + Math.floor(sl / 0x100000000)) | 0; hl[4] = sl | 0;
    sl = (hl[5] >>> 0) + (fl >>> 0); hh[5] = (hh[5] + fh + Math.floor(sl / 0x100000000)) | 0; hl[5] = sl | 0;
    sl = (hl[6] >>> 0) + (gl >>> 0); hh[6] = (hh[6] + gh + Math.floor(sl / 0x100000000)) | 0; hl[6] = sl | 0;
    sl = (hl[7] >>> 0) + (hl7 >>> 0); hh[7] = (hh[7] + hh7 + Math.floor(sl / 0x100000000)) | 0; hl[7] = sl | 0;
  }

  var out = new Uint8Array(64);
  for (var j = 0; j < 8; j++) {
    out[8 * j] = (hh[j] >>> 24) & 0xff;
    out[8 * j + 1] = (hh[j] >>> 16) & 0xff;
    out[8 * j + 2] = (hh[j] >>> 8) & 0xff;
    out[8 * j + 3] = hh[j] & 0xff;
    out[8 * j + 4] = (hl[j] >>> 24) & 0xff;
    out[8 * j + 5] = (hl[j] >>> 16) & 0xff;
    out[8 * j + 6] = (hl[j] >>> 8) & 0xff;
    out[8 * j + 7] = hl[j] & 0xff;
  }
  return out;
}

/* ---------------- AES-256 ---------------- */

// S-box computed from first principles (GF(2^8) inverse + affine map)
// rather than embedding the table.
var AES_SBOX = new Uint8Array(256);
(function () {
  var exp = new Uint8Array(256);
  var log = new Uint8Array(256);
  var x = 1;
  for (var i = 0; i < 255; i++) {
    exp[i] = x;
    log[x] = i;
    // multiply by generator 3 = x * 2 ^ x
    var x2 = (x << 1) ^ ((x & 0x80) ? 0x11b : 0);
    x = (x2 ^ x) & 0xff;
  }
  for (i = 0; i < 256; i++) {
    var inv = i === 0 ? 0 : exp[(255 - log[i]) % 255];
    var s = inv;
    s ^= ((inv << 1) | (inv >> 7)) & 0xff;
    s ^= ((inv << 2) | (inv >> 6)) & 0xff;
    s ^= ((inv << 3) | (inv >> 5)) & 0xff;
    s ^= ((inv << 4) | (inv >> 4)) & 0xff;
    AES_SBOX[i] = s ^ 0x63;
  }
})();

// AES-256 key schedule: 60 round-key words as a 240-byte array.
function aes256ExpandKey(key) {
  var rk = new Uint8Array(240);
  rk.set(key);
  var rcon = 1;
  for (var i = 32; i < 240; i += 4) {
    var t0 = rk[i - 4], t1 = rk[i - 3], t2 = rk[i - 2], t3 = rk[i - 1];
    if (i % 32 === 0) {
      var tmp = t0;
      t0 = AES_SBOX[t1] ^ rcon;
      t1 = AES_SBOX[t2];
      t2 = AES_SBOX[t3];
      t3 = AES_SBOX[tmp];
      rcon = ((rcon << 1) ^ ((rcon & 0x80) ? 0x11b : 0)) & 0xff;
    } else if (i % 32 === 16) {
      t0 = AES_SBOX[t0];
      t1 = AES_SBOX[t1];
      t2 = AES_SBOX[t2];
      t3 = AES_SBOX[t3];
    }
    rk[i] = rk[i - 32] ^ t0;
    rk[i + 1] = rk[i - 31] ^ t1;
    rk[i + 2] = rk[i - 30] ^ t2;
    rk[i + 3] = rk[i - 29] ^ t3;
  }
  return rk;
}

function xtime(b) {
  return ((b << 1) ^ ((b & 0x80) ? 0x11b : 0)) & 0xff;
}

// Encrypts the 16 bytes at inp into out (may alias) with expanded key rk.
function aes256EncryptBlock(rk, inp, out) {
  var s = new Uint8Array(16);
  var i, r, t;
  for (i = 0; i < 16; i++) s[i] = inp[i] ^ rk[i];
  for (r = 1; r <= 14; r++) {
    // SubBytes
    for (i = 0; i < 16; i++) s[i] = AES_SBOX[s[i]];
    // ShiftRows (state is column-major: byte i = row i%4, col i>>2)
    t = s[1]; s[1] = s[5]; s[5] = s[9]; s[9] = s[13]; s[13] = t;
    t = s[2]; s[2] = s[10]; s[10] = t; t = s[6]; s[6] = s[14]; s[14] = t;
    t = s[15]; s[15] = s[11]; s[11] = s[7]; s[7] = s[3]; s[3] = t;
    // MixColumns (skipped in final round)
    if (r < 14) {
      for (i = 0; i < 16; i += 4) {
        var a0 = s[i], a1 = s[i + 1], a2 = s[i + 2], a3 = s[i + 3];
        var all = a0 ^ a1 ^ a2 ^ a3;
        s[i] = a0 ^ all ^ xtime(a0 ^ a1);
        s[i + 1] = a1 ^ all ^ xtime(a1 ^ a2);
        s[i + 2] = a2 ^ all ^ xtime(a2 ^ a3);
        s[i + 3] = a3 ^ all ^ xtime(a3 ^ a0);
      }
    }
    // AddRoundKey
    for (i = 0; i < 16; i++) s[i] ^= rk[16 * r + i];
  }
  for (i = 0; i < 16; i++) out[i] = s[i];
}

/* ---------------- AES-256-GCM ---------------- */

// GF(2^128) multiply, operands/result as 4 big-endian 32-bit words.
function gcmMul(x, h) {
  var z0 = 0, z1 = 0, z2 = 0, z3 = 0;
  var v0 = x[0], v1 = x[1], v2 = x[2], v3 = x[3];
  for (var i = 0; i < 128; i++) {
    if ((h[i >> 5] >>> (31 - (i & 31))) & 1) {
      z0 ^= v0; z1 ^= v1; z2 ^= v2; z3 ^= v3;
    }
    var lsb = v3 & 1;
    v3 = (v3 >>> 1) | ((v2 & 1) << 31);
    v2 = (v2 >>> 1) | ((v1 & 1) << 31);
    v1 = (v1 >>> 1) | ((v0 & 1) << 31);
    v0 = v0 >>> 1;
    if (lsb) v0 ^= 0xe1000000;
  }
  return [z0 | 0, z1 | 0, z2 | 0, z3 | 0];
}

function ghashUpdate(y, h, bytes, off) {
  var x = [
    y[0] ^ ((bytes[off] << 24) | (bytes[off + 1] << 16) | (bytes[off + 2] << 8) | bytes[off + 3]),
    y[1] ^ ((bytes[off + 4] << 24) | (bytes[off + 5] << 16) | (bytes[off + 6] << 8) | bytes[off + 7]),
    y[2] ^ ((bytes[off + 8] << 24) | (bytes[off + 9] << 16) | (bytes[off + 10] << 8) | bytes[off + 11]),
    y[3] ^ ((bytes[off + 12] << 24) | (bytes[off + 13] << 16) | (bytes[off + 14] << 8) | bytes[off + 15])
  ];
  return gcmMul(x, h);
}

// Core GCM with 96-bit IV and no AAD. Returns {data, tag}.
function gcmCrypt(rk, iv, input) {
  var h = new Uint8Array(16);
  aes256EncryptBlock(rk, h, h);
  var hWords = [
    (h[0] << 24) | (h[1] << 16) | (h[2] << 8) | h[3],
    (h[4] << 24) | (h[5] << 16) | (h[6] << 8) | h[7],
    (h[8] << 24) | (h[9] << 16) | (h[10] << 8) | h[11],
    (h[12] << 24) | (h[13] << 16) | (h[14] << 8) | h[15]
  ];

  var ctr = new Uint8Array(16);
  ctr.set(iv);
  ctr[15] = 1;
  var ek0 = new Uint8Array(16);
  aes256EncryptBlock(rk, ctr, ek0); // E(K, J0) for the tag

  var out = new Uint8Array(input.length);
  var ks = new Uint8Array(16);
  var counter = 1;
  for (var p = 0; p < input.length; p += 16) {
    counter++;
    ctr[12] = (counter >>> 24) & 0xff;
    ctr[13] = (counter >>> 16) & 0xff;
    ctr[14] = (counter >>> 8) & 0xff;
    ctr[15] = counter & 0xff;
    aes256EncryptBlock(rk, ctr, ks);
    var n = Math.min(16, input.length - p);
    for (var i = 0; i < n; i++) out[p + i] = input[p + i] ^ ks[i];
  }
  return { out: out, hWords: hWords, ek0: ek0 };
}

function gcmTag(hWords, ek0, ciphertext) {
  var y = [0, 0, 0, 0];
  var full = ciphertext.length - (ciphertext.length % 16);
  for (var p = 0; p < full; p += 16) {
    y = ghashUpdate(y, hWords, ciphertext, p);
  }
  if (ciphertext.length > full) {
    var pad = new Uint8Array(16);
    pad.set(ciphertext.subarray(full));
    y = ghashUpdate(y, hWords, pad, 0);
  }
  // length block: 64-bit AAD bits (0) || 64-bit ciphertext bits
  var lenBlk = new Uint8Array(16);
  var bits = ciphertext.length * 8;
  lenBlk[8] = 0; // < 2^56 bytes, top bytes stay 0
  lenBlk[10] = (bits / 0x10000000000) & 0xff;
  lenBlk[11] = (bits / 0x100000000) & 0xff;
  lenBlk[12] = (bits >>> 24) & 0xff;
  lenBlk[13] = (bits >>> 16) & 0xff;
  lenBlk[14] = (bits >>> 8) & 0xff;
  lenBlk[15] = bits & 0xff;
  y = ghashUpdate(y, hWords, lenBlk, 0);
  var tag = new Uint8Array(16);
  for (var j = 0; j < 4; j++) {
    tag[4 * j] = ((y[j] >>> 24) & 0xff) ^ ek0[4 * j];
    tag[4 * j + 1] = ((y[j] >>> 16) & 0xff) ^ ek0[4 * j + 1];
    tag[4 * j + 2] = ((y[j] >>> 8) & 0xff) ^ ek0[4 * j + 2];
    tag[4 * j + 3] = (y[j] & 0xff) ^ ek0[4 * j + 3];
  }
  return tag;
}

// Returns ciphertext || 16-byte tag (WebCrypto AES-GCM layout).
function aesGcmEncrypt(key, iv, plaintext) {
  var rk = aes256ExpandKey(key);
  var r = gcmCrypt(rk, iv, plaintext);
  var tag = gcmTag(r.hWords, r.ek0, r.out);
  return concatBytes(r.out, tag);
}

// Input is ciphertext || 16-byte tag. Returns plaintext or null on bad tag.
function aesGcmDecrypt(key, iv, data) {
  if (data.length < 16) return null;
  var ciphertext = data.subarray(0, data.length - 16);
  var tag = data.subarray(data.length - 16);
  var rk = aes256ExpandKey(key);
  var r = gcmCrypt(rk, iv, ciphertext);
  var expected = gcmTag(r.hWords, r.ek0, ciphertext);
  var diff = 0;
  for (var i = 0; i < 16; i++) diff |= expected[i] ^ tag[i];
  if (diff !== 0) return null;
  return r.out;
}

/* ---------------- Ed25519 (derived from TweetNaCl.js, public domain) ---------------- */

function gf(init) {
  var r = new Float64Array(16);
  if (init) for (var i = 0; i < init.length; i++) r[i] = init[i];
  return r;
}

var GF0 = gf();
var GF1 = gf([1]);
var ED_D2 = gf([0xf159, 0x26b2, 0x9b94, 0xebd6, 0xb156, 0x8283, 0x149a, 0x00e0, 0xd130, 0xeef3, 0x80f2, 0x198e, 0xfce7, 0x56df, 0xd9dc, 0x2406]);
var ED_X = gf([0xd51a, 0x8f25, 0x2d60, 0xc956, 0xa7b2, 0x9525, 0xc760, 0x692c, 0xdc5c, 0xfdd6, 0xe231, 0xc0a4, 0x53fe, 0xcd6e, 0x36d3, 0x2169]);
var ED_Y = gf([0x6658, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666]);

function set25519(r, a) {
  for (var i = 0; i < 16; i++) r[i] = a[i];
}

function car25519(o) {
  var c = 1;
  for (var i = 0; i < 16; i++) {
    var v = o[i] + c + 65535;
    c = Math.floor(v / 65536);
    o[i] = v - c * 65536;
  }
  o[0] += c - 1 + 37 * (c - 1);
}

function sel25519(p, q, b) {
  var c = ~(b - 1);
  for (var i = 0; i < 16; i++) {
    var t = c & (p[i] ^ q[i]);
    p[i] ^= t;
    q[i] ^= t;
  }
}

function pack25519(o, n) {
  var i, j, b;
  var m = gf(), t = gf();
  for (i = 0; i < 16; i++) t[i] = n[i];
  car25519(t);
  car25519(t);
  car25519(t);
  for (j = 0; j < 2; j++) {
    m[0] = t[0] - 0xffed;
    for (i = 1; i < 15; i++) {
      m[i] = t[i] - 0xffff - ((m[i - 1] >> 16) & 1);
      m[i - 1] &= 0xffff;
    }
    m[15] = t[15] - 0x7fff - ((m[14] >> 16) & 1);
    b = (m[15] >> 16) & 1;
    m[14] &= 0xffff;
    sel25519(t, m, 1 - b);
  }
  for (i = 0; i < 16; i++) {
    o[2 * i] = t[i] & 0xff;
    o[2 * i + 1] = t[i] >> 8;
  }
}

function par25519(a) {
  var d = new Uint8Array(32);
  pack25519(d, a);
  return d[0] & 1;
}

function fadd(o, a, b) {
  for (var i = 0; i < 16; i++) o[i] = a[i] + b[i];
}

function fsub(o, a, b) {
  for (var i = 0; i < 16; i++) o[i] = a[i] - b[i];
}

function fmul(o, a, b) {
  var t = new Float64Array(31);
  var i, j;
  for (i = 0; i < 16; i++) {
    var ai = a[i];
    for (j = 0; j < 16; j++) t[i + j] += ai * b[j];
  }
  for (i = 0; i < 15; i++) t[i] += 38 * t[i + 16];
  for (i = 0; i < 16; i++) o[i] = t[i];
  car25519(o);
  car25519(o);
}

function fsquare(o, a) {
  fmul(o, a, a);
}

function inv25519(o, inp) {
  var c = gf();
  var a;
  for (a = 0; a < 16; a++) c[a] = inp[a];
  for (a = 253; a >= 0; a--) {
    fsquare(c, c);
    if (a !== 2 && a !== 4) fmul(c, c, inp);
  }
  for (a = 0; a < 16; a++) o[a] = c[a];
}

// Extended-coordinate point addition (p += q).
function edAdd(p, q) {
  var a = gf(), b = gf(), c = gf(), d = gf(), e = gf(), f = gf(), g = gf(), h = gf(), t = gf();
  fsub(a, p[1], p[0]);
  fsub(t, q[1], q[0]);
  fmul(a, a, t);
  fadd(b, p[0], p[1]);
  fadd(t, q[0], q[1]);
  fmul(b, b, t);
  fmul(c, p[3], q[3]);
  fmul(c, c, ED_D2);
  fmul(d, p[2], q[2]);
  fadd(d, d, d);
  fsub(e, b, a);
  fsub(f, d, c);
  fadd(g, d, c);
  fadd(h, b, a);
  fmul(p[0], e, f);
  fmul(p[1], h, g);
  fmul(p[2], g, f);
  fmul(p[3], e, h);
}

function cswap(p, q, b) {
  for (var i = 0; i < 4; i++) sel25519(p[i], q[i], b);
}

function edPack(r, p) {
  var tx = gf(), ty = gf(), zi = gf();
  inv25519(zi, p[2]);
  fmul(tx, p[0], zi);
  fmul(ty, p[1], zi);
  pack25519(r, ty);
  r[31] ^= par25519(tx) << 7;
}

function edScalarmult(p, q, s) {
  set25519(p[0], GF0);
  set25519(p[1], GF1);
  set25519(p[2], GF1);
  set25519(p[3], GF0);
  for (var i = 255; i >= 0; --i) {
    var b = (s[(i / 8) | 0] >> (i & 7)) & 1;
    cswap(p, q, b);
    edAdd(q, p);
    edAdd(p, p);
    cswap(p, q, b);
  }
}

function edScalarbase(p, s) {
  var q = [gf(), gf(), gf(), gf()];
  set25519(q[0], ED_X);
  set25519(q[1], ED_Y);
  set25519(q[2], GF1);
  fmul(q[3], ED_X, ED_Y);
  edScalarmult(p, q, s);
}

var ED_L = new Float64Array([0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10]);

function modL(r, x) {
  var carry, i, j, k;
  for (i = 63; i >= 32; --i) {
    carry = 0;
    for (j = i - 32, k = i - 12; j < k; ++j) {
      x[j] += carry - 16 * x[i] * ED_L[j - (i - 32)];
      carry = Math.floor((x[j] + 128) / 256);
      x[j] -= carry * 256;
    }
    x[j] += carry;
    x[i] = 0;
  }
  carry = 0;
  for (j = 0; j < 32; j++) {
    x[j] += carry - (x[31] >> 4) * ED_L[j];
    carry = x[j] >> 8;
    x[j] &= 255;
  }
  for (j = 0; j < 32; j++) x[j] -= carry * ED_L[j];
  for (i = 0; i < 32; i++) {
    x[i + 1] += x[i] >> 8;
    r[i] = x[i] & 255;
  }
}

function edReduce(r) {
  var x = new Float64Array(64);
  var i;
  for (i = 0; i < 64; i++) x[i] = r[i];
  for (i = 0; i < 64; i++) r[i] = 0;
  modL(r, x);
}

// Public key (32 bytes) from a 32-byte seed; matches RFC 8032 / WebCrypto.
function ed25519PublicKey(seed) {
  var d = sha512(seed);
  d[0] &= 248;
  d[31] &= 127;
  d[31] |= 64;
  var p = [gf(), gf(), gf(), gf()];
  edScalarbase(p, d);
  var pk = new Uint8Array(32);
  edPack(pk, p);
  return pk;
}

// Detached 64-byte signature; matches RFC 8032 / WebCrypto Ed25519.
function ed25519Sign(seed, msg) {
  var d = sha512(seed);
  d[0] &= 248;
  d[31] &= 127;
  d[31] |= 64;
  var pk = ed25519PublicKey(seed);

  var r = sha512(concatBytes(d.subarray(32), msg));
  edReduce(r);
  var p = [gf(), gf(), gf(), gf()];
  edScalarbase(p, r);
  var R = new Uint8Array(32);
  edPack(R, p);

  var h = sha512(concatBytes(R, pk, msg));
  edReduce(h);

  var x = new Float64Array(64);
  var i, j;
  for (i = 0; i < 32; i++) x[i] = r[i];
  for (i = 0; i < 32; i++) {
    for (j = 0; j < 32; j++) {
      x[i + j] += h[i] * d[j];
    }
  }
  var S = new Uint8Array(32);
  modL(S, x);
  return concatBytes(R, S);
}

/* ---------------- randomness ---------------- */
/* PebbleKit JS has no crypto.getRandomValues. This is a SHA-256 ratchet
 * seeded from timing + Math.random + a counter. Not as strong as a real
 * CSPRNG, but GCM IV uniqueness is guaranteed by the counter/time mixing,
 * which is the property that actually matters here (IVs and UUIDs). */

var rngState = sha256(utf8Encode('wafflelist-pebble-rng' + Date.now() + Math.random()));
var rngCounter = 0;

function rngRatchet(tag) {
  var entropy = utf8Encode('' + tag + ':' + (rngCounter++) + ':' + Date.now() + ':' + Math.random() + ':' + Math.random());
  return sha256(concatBytes(rngState, entropy));
}

function randomBytes(n) {
  var out = new Uint8Array(n);
  var off = 0;
  while (off < n) {
    rngState = rngRatchet(0);
    var block = rngRatchet(1);
    var take = Math.min(32, n - off);
    for (var i = 0; i < take; i++) out[off + i] = block[i];
    off += take;
  }
  return out;
}

function uuid4() {
  var b = randomBytes(16);
  b[6] = (b[6] & 0x0f) | 0x40;
  b[8] = (b[8] & 0x3f) | 0x80;
  var h = bytesToHex(b);
  return h.substr(0, 8) + '-' + h.substr(8, 4) + '-' + h.substr(12, 4) + '-' + h.substr(16, 4) + '-' + h.substr(20);
}

/* ---------------- Wafflelist key derivation ---------------- */
/* Mirrors src/lib/crypto.ts in the web client. */

var USER_ID_SALT = utf8Encode('wafflelist-user-id-v1');
var ENCRYPTION_SALT = utf8Encode('wafflelist-encryption-v1');
var SIGNING_SALT = utf8Encode('wafflelist-signing-v1');
var PBKDF2_ITERATIONS = 600000;

// cb(userIdHex); progress(done, total) optional.
function deriveUserIdAsync(phrase, cb, progress) {
  pbkdf2Sha256Async(utf8Encode(phrase), USER_ID_SALT, PBKDF2_ITERATIONS, function (bits) {
    cb(bytesToHex(bits));
  }, progress);
}

function deriveEncryptionKey(phrase) {
  return hkdfSha256(utf8Encode(phrase), ENCRYPTION_SALT, utf8Encode('encryption'));
}

function deriveSigningSeed(phrase) {
  return hkdfSha256(utf8Encode(phrase), SIGNING_SALT, utf8Encode('signing'));
}

// Encrypts a JS object to the web client's blob format: base64(iv || ct || tag).
function encryptBlob(key, obj) {
  var iv = randomBytes(12);
  var data = aesGcmEncrypt(key, iv, utf8Encode(JSON.stringify(obj)));
  return bytesToBase64(concatBytes(iv, data));
}

// Decrypts base64(iv || ct || tag) to a JS object, or null on failure.
function decryptBlob(key, blobB64) {
  var combined = base64ToBytes(blobB64);
  if (combined.length < 28) return null;
  var plain = aesGcmDecrypt(key, combined.subarray(0, 12), combined.subarray(12));
  if (plain === null) return null;
  return JSON.parse(utf8Decode(plain));
}

module.exports = {
  utf8Encode: utf8Encode,
  utf8Decode: utf8Decode,
  bytesToHex: bytesToHex,
  hexToBytes: hexToBytes,
  bytesToBase64: bytesToBase64,
  base64ToBytes: base64ToBytes,
  concatBytes: concatBytes,
  sha256: sha256,
  sha512: sha512,
  hmacSha256: hmacSha256,
  pbkdf2Sha256: pbkdf2Sha256,
  pbkdf2Sha256Async: pbkdf2Sha256Async,
  hkdfSha256: hkdfSha256,
  aesGcmEncrypt: aesGcmEncrypt,
  aesGcmDecrypt: aesGcmDecrypt,
  ed25519PublicKey: ed25519PublicKey,
  ed25519Sign: ed25519Sign,
  randomBytes: randomBytes,
  uuid4: uuid4,
  deriveUserIdAsync: deriveUserIdAsync,
  deriveEncryptionKey: deriveEncryptionKey,
  deriveSigningSeed: deriveSigningSeed,
  encryptBlob: encryptBlob,
  decryptBlob: decryptBlob,
  PBKDF2_ITERATIONS: PBKDF2_ITERATIONS
};
